# Partie 5 : Représentation Bag of Words

In [1]:
phrases = [
    "Le football est un sport très populaire dans le monde",
    "Le cinéma est un art qui raconte des histoires",
    "Le sport et le cinéma passionnent beaucoup de monde"
]

for p in phrases:
    print(p)

Le football est un sport très populaire dans le monde
Le cinéma est un art qui raconte des histoires
Le sport et le cinéma passionnent beaucoup de monde

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

# Création du vectoriseur
bow = CountVectorizer()

# Transformation des phrases en matrice
X_bow = bow.fit_transform(phrases)

print("Shape :", X_bow.shape)

Shape : (3, 19)

In [3]:
mots = bow.get_feature_names_out()
print("Mots extraits :")
print(mots)

Mots extraits :
['art' 'beaucoup' 'cinéma' 'dans' 'de' 'des' 'est' 'et' 'football'
 'histoires' 'le' 'monde' 'passionnent' 'populaire' 'qui' 'raconte'
 'sport' 'très' 'un']

In [4]:
X_bow_df = pd.DataFrame(X_bow.toarray(), columns=mots)
X_bow_df

,art,beaucoup,cinéma,dans,de,des,est,et,football,histoires,le,monde,passionnent,populaire,qui,raconte,sport,très,un
0,0,0,0,1,0,0,1,0,1,0,2,1,0,1,0,0,1,1,1
1,1,0,1,0,0,1,1,0,0,1,1,0,0,0,1,1,0,0,1
2,0,1,1,0,1,0,0,1,0,0,2,1,1,0,0,0,1,0,0

##  Questions

**Que représente chaque colonne de la matrice ?**
Chaque colonne représente un mot unique du vocabulaire et chaque ligne représente les phrases, et la valeur dans la case indique combien de fois ce mot apparaît dans la phrase.

**Quelles sont les limites du modèle Bag of Words ?**
- Il ignore l'ordre des mots.
- Il ne comprend pas le sens des mots comme « voiture » et « automobile » sont deux colonnes sans lien entre eux.
- Les mots très fréquents (« le », « est », « un ») prennent beaucoup de place alors qu'ils n'apportent pas beaucoup d'information.

**Que perd-on en supprimant l'ordre des mots ?**
On perd le sens de la phrase, les négations et le contexte entre les mots.

# Partie 6 : Représentation TF-IDF

In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Création du vectoriseur TF-IDF
tfidf = TfidfVectorizer()

# Transformation des mêmes phrases
X_tfidf = tfidf.fit_transform(phrases)

print("Shape :", X_tfidf.shape)

Shape : (3, 19)

In [6]:
X_tfidf_df = pd.DataFrame(X_tfidf.toarray(), columns=tfidf.get_feature_names_out())
X_tfidf_df.round(2)

,art,beaucoup,cinéma,dans,de,des,est,et,football,histoires,le,monde,passionnent,populaire,qui,raconte,sport,très,un
0,0.00,0.00,0.00,0.36,0.00,0.00,0.27,0.00,0.36,0.00,0.43,0.27,0.00,0.36,0.00,0.00,0.27,0.36,0.27
1,0.38,0.00,0.29,0.00,0.00,0.38,0.29,0.00,0.00,0.38,0.22,0.00,0.00,0.00,0.38,0.38,0.00,0.00,0.29
2,0.00,0.37,0.28,0.00,0.37,0.00,0.00,0.37,0.00,0.00,0.44,0.28,0.37,0.00,0.00,0.00,0.28,0.00,0.00

In [7]:
print("Bag of Words (comptage) :")
display(X_bow_df)

print("TF-IDF (poids arrondis) :")
display(X_tfidf_df.round(2))

Bag of Words (comptage) :

,art,beaucoup,cinéma,dans,de,des,est,et,football,histoires,le,monde,passionnent,populaire,qui,raconte,sport,très,un
0,0,0,0,1,0,0,1,0,1,0,2,1,0,1,0,0,1,1,1
1,1,0,1,0,0,1,1,0,0,1,1,0,0,0,1,1,0,0,1
2,0,1,1,0,1,0,0,1,0,0,2,1,1,0,0,0,1,0,0

TF-IDF (poids arrondis) :

,art,beaucoup,cinéma,dans,de,des,est,et,football,histoires,le,monde,passionnent,populaire,qui,raconte,sport,très,un
0,0.00,0.00,0.00,0.36,0.00,0.00,0.27,0.00,0.36,0.00,0.43,0.27,0.00,0.36,0.00,0.00,0.27,0.36,0.27
1,0.38,0.00,0.29,0.00,0.00,0.38,0.29,0.00,0.00,0.38,0.22,0.00,0.00,0.00,0.38,0.38,0.00,0.00,0.29
2,0.00,0.37,0.28,0.00,0.37,0.00,0.00,0.37,0.00,0.00,0.44,0.28,0.37,0.00,0.00,0.00,0.28,0.00,0.00

In [8]:
# Exemple : on compare quelques mots pour la phrase 1
print("Phrase 1 :", phrases[0])
print()
for mot in ["le", "est", "football", "sport"]:
    print(mot, "-> BoW :", X_bow_df[mot][0], "| TF-IDF :", round(X_tfidf_df[mot][0], 2))

Phrase 1 : Le football est un sport très populaire dans le monde

le -> BoW : 2 | TF-IDF : 0.43
est -> BoW : 1 | TF-IDF : 0.27
football -> BoW : 1 | TF-IDF : 0.36
sport -> BoW : 1 | TF-IDF : 0.27

## Questions

**Quelle est la différence principale entre BoW et TF-IDF ?**
BoW compte simplement le nombre de fois où un mot apparaît.TF-IDF multiplie ce nombre par un facteur qui mesure la rareté du mot dans l'ensemble des documents, un mot présent partout est pénalisé et un mot rare et spécifique est valorisé.

**Pourquoi les mots très fréquents ont-ils souvent un poids faible ?**
Parce que le TF-IDF l'inverse document frequency diminue quand un mot apparaît dans beaucoup de documents. Un mot comme "le", "est" est présent dans presque toutes les phrases, donc il ne permet pas de les distinguer : son poids est réduit.

**Exemple concret où TF-IDF est plus utile que BoW :**
Dans un classement d'articles. Si on cherche "football" dans des milliers d'articles, le mot "le" apparaît très souvent partout et ne sert à rien, alors que "football" est rare. TF-IDF met en importance les articles vraiment liés au football, alors que BoW serait pollué par les mots courants.